- src: https://github.com/NiCalderon/homedir-hierarchy.git
  version: main

- src: https://github.com/NiCalderon/homedir-zsh.git
  version: main

- src: https://github.com/NiCalderon/homedir-login.git
  version: main
